// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.rakuten.reels.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * User profile data model
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class UserProfile (
  val id: String,
  val name: String,
  val avatar: String? = null,
  val reelsCount: Long,
  val followersCount: Long,
  val followingCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserProfile {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val avatar = pigeonVar_list[2] as String?
      val reelsCount = pigeonVar_list[3] as Long
      val followersCount = pigeonVar_list[4] as Long
      val followingCount = pigeonVar_list[5] as Long
      return UserProfile(id, name, avatar, reelsCount, followersCount, followingCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      avatar,
      reelsCount,
      followersCount,
      followingCount,
    )
  }
}

/**
 * Application preferences data model
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AppPreferences (
  val darkMode: Boolean,
  val language: String,
  val notificationsEnabled: Boolean,
  val autoPlayVideos: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppPreferences {
      val darkMode = pigeonVar_list[0] as Boolean
      val language = pigeonVar_list[1] as String
      val notificationsEnabled = pigeonVar_list[2] as Boolean
      val autoPlayVideos = pigeonVar_list[3] as Boolean
      return AppPreferences(darkMode, language, notificationsEnabled, autoPlayVideos)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      darkMode,
      language,
      notificationsEnabled,
      autoPlayVideos,
    )
  }
}

/**
 * Reel data model
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ReelData (
  val id: String,
  val title: String,
  val description: String? = null,
  val videoUrl: String,
  val thumbnailUrl: String? = null,
  val likeCount: Long,
  val viewCount: Long,
  val isLiked: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReelData {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val description = pigeonVar_list[2] as String?
      val videoUrl = pigeonVar_list[3] as String
      val thumbnailUrl = pigeonVar_list[4] as String?
      val likeCount = pigeonVar_list[5] as Long
      val viewCount = pigeonVar_list[6] as Long
      val isLiked = pigeonVar_list[7] as Boolean
      return ReelData(id, title, description, videoUrl, thumbnailUrl, likeCount, viewCount, isLiked)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      description,
      videoUrl,
      thumbnailUrl,
      likeCount,
      viewCount,
      isLiked,
    )
  }
}

/**
 * Analytics event data model
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AnalyticsEvent (
  val eventName: String,
  val parameters: Map<String, Any?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AnalyticsEvent {
      val eventName = pigeonVar_list[0] as String
      val parameters = pigeonVar_list[1] as Map<String, Any?>
      return AnalyticsEvent(eventName, parameters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      eventName,
      parameters,
    )
  }
}
private open class ReelsApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserProfile.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppPreferences.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReelData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnalyticsEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is UserProfile -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AppPreferences -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ReelData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AnalyticsEvent -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Host API - Android methods callable from Flutter
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ReelsHostApi {
  /** Get current user profile */
  fun getUserProfile(): UserProfile
  /** Share a reel using native Android sharing */
  fun shareReel(reelId: String, title: String, description: String?)
  /** Open a native Android screen */
  fun openNativeScreen(screenName: String, params: Map<String, Any?>)
  /** Log analytics event to native analytics system */
  fun logAnalyticsEvent(eventName: String, parameters: Map<String, Any?>)
  /** Show native Android toast message */
  fun showToast(message: String)
  /** Get app preferences from native storage */
  fun getAppPreferences(): AppPreferences
  /** Save app preferences to native storage */
  fun saveAppPreferences(preferences: AppPreferences)
  /** Get list of reels from native data source */
  fun getReels(page: Long, limit: Long): List<ReelData>
  /** Like/unlike a reel */
  fun toggleReelLike(reelId: String, isLiked: Boolean)
  /** Report content */
  fun reportContent(reelId: String, reason: String)
  /** Navigate back to native screen */
  fun navigateBack()

  companion object {
    /** The codec used by ReelsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ReelsApiPigeonCodec()
    }
    /** Sets up an instance of `ReelsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ReelsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.getUserProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getUserProfile())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.shareReel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reelIdArg = args[0] as String
            val titleArg = args[1] as String
            val descriptionArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.shareReel(reelIdArg, titleArg, descriptionArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.openNativeScreen$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val screenNameArg = args[0] as String
            val paramsArg = args[1] as Map<String, Any?>
            val wrapped: List<Any?> = try {
              api.openNativeScreen(screenNameArg, paramsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.logAnalyticsEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventNameArg = args[0] as String
            val parametersArg = args[1] as Map<String, Any?>
            val wrapped: List<Any?> = try {
              api.logAnalyticsEvent(eventNameArg, parametersArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.showToast$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.showToast(messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.getAppPreferences$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAppPreferences())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.saveAppPreferences$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val preferencesArg = args[0] as AppPreferences
            val wrapped: List<Any?> = try {
              api.saveAppPreferences(preferencesArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.getReels$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pageArg = args[0] as Long
            val limitArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getReels(pageArg, limitArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.toggleReelLike$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reelIdArg = args[0] as String
            val isLikedArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.toggleReelLike(reelIdArg, isLikedArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.reportContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reelIdArg = args[0] as String
            val reasonArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.reportContent(reelIdArg, reasonArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reels_flutter.ReelsHostApi.navigateBack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.navigateBack()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API - Flutter methods callable from Android
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ReelsFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ReelsFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ReelsApiPigeonCodec()
    }
  }
  /** Update user profile data in Flutter */
  fun onUserProfileUpdated(profileArg: UserProfile, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.reels_flutter.ReelsFlutterApi.onUserProfileUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(profileArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Update app preferences in Flutter */
  fun onPreferencesChanged(preferencesArg: AppPreferences, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.reels_flutter.ReelsFlutterApi.onPreferencesChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(preferencesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Trigger refresh of reels list */
  fun refreshReels(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.reels_flutter.ReelsFlutterApi.refreshReels$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Navigate to specific screen in Flutter */
  fun navigateToScreen(screenNameArg: String, paramsArg: Map<String, Any?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.reels_flutter.ReelsFlutterApi.navigateToScreen$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(screenNameArg, paramsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Update theme/appearance */
  fun updateTheme(isDarkModeArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.reels_flutter.ReelsFlutterApi.updateTheme$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(isDarkModeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Handle deep link */
  fun handleDeepLink(urlArg: String, paramsArg: Map<String, Any?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.reels_flutter.ReelsFlutterApi.handleDeepLink$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(urlArg, paramsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Show message/notification in Flutter */
  fun showMessage(messageArg: String, typeArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.reels_flutter.ReelsFlutterApi.showMessage$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg, typeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Update reel data (for real-time updates) */
  fun updateReelData(reelsArg: List<ReelData>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.reels_flutter.ReelsFlutterApi.updateReelData$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(reelsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
