// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Collect data model - represents a user's post/collection item
///
/// Generated class from Pigeon that represents data sent in messages.
struct CollectData {
  var id: String
  var content: String? = nil
  var name: String? = nil
  var likes: Int64? = nil
  var comments: Int64? = nil
  var recollects: Int64? = nil
  var isLiked: Bool? = nil
  var isCollected: Bool? = nil
  var trackingTag: String? = nil
  var userId: String? = nil
  var userName: String? = nil
  var userProfileImage: String? = nil
  var itemName: String? = nil
  var itemImageUrl: String? = nil
  var imageUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CollectData? {
    let id = pigeonVar_list[0] as! String
    let content: String? = nilOrValue(pigeonVar_list[1])
    let name: String? = nilOrValue(pigeonVar_list[2])
    let likes: Int64? = nilOrValue(pigeonVar_list[3])
    let comments: Int64? = nilOrValue(pigeonVar_list[4])
    let recollects: Int64? = nilOrValue(pigeonVar_list[5])
    let isLiked: Bool? = nilOrValue(pigeonVar_list[6])
    let isCollected: Bool? = nilOrValue(pigeonVar_list[7])
    let trackingTag: String? = nilOrValue(pigeonVar_list[8])
    let userId: String? = nilOrValue(pigeonVar_list[9])
    let userName: String? = nilOrValue(pigeonVar_list[10])
    let userProfileImage: String? = nilOrValue(pigeonVar_list[11])
    let itemName: String? = nilOrValue(pigeonVar_list[12])
    let itemImageUrl: String? = nilOrValue(pigeonVar_list[13])
    let imageUrl: String? = nilOrValue(pigeonVar_list[14])

    return CollectData(
      id: id,
      content: content,
      name: name,
      likes: likes,
      comments: comments,
      recollects: recollects,
      isLiked: isLiked,
      isCollected: isCollected,
      trackingTag: trackingTag,
      userId: userId,
      userName: userName,
      userProfileImage: userProfileImage,
      itemName: itemName,
      itemImageUrl: itemImageUrl,
      imageUrl: imageUrl
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      content,
      name,
      likes,
      comments,
      recollects,
      isLiked,
      isCollected,
      trackingTag,
      userId,
      userName,
      userProfileImage,
      itemName,
      itemImageUrl,
      imageUrl,
    ]
  }
}

/// Analytics event data
///
/// Generated class from Pigeon that represents data sent in messages.
struct AnalyticsEvent {
  var eventName: String
  var eventProperties: [String?: String?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnalyticsEvent? {
    let eventName = pigeonVar_list[0] as! String
    let eventProperties = pigeonVar_list[1] as! [String?: String?]

    return AnalyticsEvent(
      eventName: eventName,
      eventProperties: eventProperties
    )
  }
  func toList() -> [Any?] {
    return [
      eventName,
      eventProperties,
    ]
  }
}

/// Share data for social sharing
///
/// Generated class from Pigeon that represents data sent in messages.
struct ShareData {
  var videoId: String
  var videoUrl: String
  var title: String
  var description: String
  var thumbnailUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ShareData? {
    let videoId = pigeonVar_list[0] as! String
    let videoUrl = pigeonVar_list[1] as! String
    let title = pigeonVar_list[2] as! String
    let description = pigeonVar_list[3] as! String
    let thumbnailUrl: String? = nilOrValue(pigeonVar_list[4])

    return ShareData(
      videoId: videoId,
      videoUrl: videoUrl,
      title: title,
      description: description,
      thumbnailUrl: thumbnailUrl
    )
  }
  func toList() -> [Any?] {
    return [
      videoId,
      videoUrl,
      title,
      description,
      thumbnailUrl,
    ]
  }
}

/// Screen state data for native tracking
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScreenStateData {
  var screenName: String
  var state: String
  var timestamp: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScreenStateData? {
    let screenName = pigeonVar_list[0] as! String
    let state = pigeonVar_list[1] as! String
    let timestamp: Int64? = nilOrValue(pigeonVar_list[2])

    return ScreenStateData(
      screenName: screenName,
      state: state,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      screenName,
      state,
      timestamp,
    ]
  }
}

/// Video state data for playback tracking
///
/// Generated class from Pigeon that represents data sent in messages.
struct VideoStateData {
  var videoId: String
  var state: String
  var position: Int64? = nil
  var duration: Int64? = nil
  var timestamp: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoStateData? {
    let videoId = pigeonVar_list[0] as! String
    let state = pigeonVar_list[1] as! String
    let position: Int64? = nilOrValue(pigeonVar_list[2])
    let duration: Int64? = nilOrValue(pigeonVar_list[3])
    let timestamp: Int64? = nilOrValue(pigeonVar_list[4])

    return VideoStateData(
      videoId: videoId,
      state: state,
      position: position,
      duration: duration,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      videoId,
      state,
      position,
      duration,
      timestamp,
    ]
  }
}

private class PigeonGeneratedPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CollectData.fromList(self.readValue() as! [Any?])
    case 130:
      return AnalyticsEvent.fromList(self.readValue() as! [Any?])
    case 131:
      return ShareData.fromList(self.readValue() as! [Any?])
    case 132:
      return ScreenStateData.fromList(self.readValue() as! [Any?])
    case 133:
      return VideoStateData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonGeneratedPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CollectData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AnalyticsEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ShareData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ScreenStateData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? VideoStateData {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonGeneratedPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonGeneratedPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonGeneratedPigeonCodecWriter(data: data)
  }
}

class PigeonGeneratedPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonGeneratedPigeonCodec(readerWriter: PigeonGeneratedPigeonCodecReaderWriter())
}


/// API for accessing user authentication token from native
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ReelsFlutterTokenApi {
  /// Get the current access token from native platform
  func getAccessToken(completion: @escaping (Result<String?, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ReelsFlutterTokenApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonGeneratedPigeonCodec.shared }
  /// Sets up an instance of `ReelsFlutterTokenApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ReelsFlutterTokenApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Get the current access token from native platform
    let getAccessTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reels_flutter.ReelsFlutterTokenApi.getAccessToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAccessTokenChannel.setMessageHandler { _, reply in
        api.getAccessToken { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAccessTokenChannel.setMessageHandler(nil)
    }
  }
}
/// API for getting initial Collect data from native
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ReelsFlutterContextApi {
  /// Get the Collect data that was used to open this screen
  /// @param generation The generation number of the screen instance
  /// @return CollectData object if opened from a Collect, null otherwise
  /// If null, Flutter will show "no videos" screen
  func getInitialCollect(generation: Int64) throws -> CollectData?
  /// Get the current generation number from native
  /// @return Current generation number
  func getCurrentGeneration() throws -> Int64
  /// Check if debug mode is enabled
  /// @return true if debug mode is enabled, false otherwise
  func isDebugMode() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ReelsFlutterContextApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonGeneratedPigeonCodec.shared }
  /// Sets up an instance of `ReelsFlutterContextApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ReelsFlutterContextApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Get the Collect data that was used to open this screen
    /// @param generation The generation number of the screen instance
    /// @return CollectData object if opened from a Collect, null otherwise
    /// If null, Flutter will show "no videos" screen
    let getInitialCollectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reels_flutter.ReelsFlutterContextApi.getInitialCollect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInitialCollectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let generationArg = args[0] as! Int64
        do {
          let result = try api.getInitialCollect(generation: generationArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getInitialCollectChannel.setMessageHandler(nil)
    }
    /// Get the current generation number from native
    /// @return Current generation number
    let getCurrentGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reels_flutter.ReelsFlutterContextApi.getCurrentGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentGenerationChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCurrentGeneration()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCurrentGenerationChannel.setMessageHandler(nil)
    }
    /// Check if debug mode is enabled
    /// @return true if debug mode is enabled, false otherwise
    let isDebugModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reels_flutter.ReelsFlutterContextApi.isDebugMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isDebugModeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isDebugMode()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isDebugModeChannel.setMessageHandler(nil)
    }
  }
}
/// API for sending analytics events to native analytics SDK
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ReelsFlutterAnalyticsApiProtocol {
  /// Track a custom analytics event
  func trackEvent(event eventArg: AnalyticsEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ReelsFlutterAnalyticsApi: ReelsFlutterAnalyticsApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonGeneratedPigeonCodec {
    return PigeonGeneratedPigeonCodec.shared
  }
  /// Track a custom analytics event
  func trackEvent(event eventArg: AnalyticsEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterAnalyticsApi.trackEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
/// API for notifying native about button interactions
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ReelsFlutterButtonEventsApiProtocol {
  /// Called before like button is clicked (for optimistic UI)
  func onBeforeLikeButtonClick(videoId videoIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called after like button click completes (with updated state)
  func onAfterLikeButtonClick(videoId videoIdArg: String, isLiked isLikedArg: Bool, likeCount likeCountArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when share button is clicked
  func onShareButtonClick(shareData shareDataArg: ShareData, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ReelsFlutterButtonEventsApi: ReelsFlutterButtonEventsApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonGeneratedPigeonCodec {
    return PigeonGeneratedPigeonCodec.shared
  }
  /// Called before like button is clicked (for optimistic UI)
  func onBeforeLikeButtonClick(videoId videoIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterButtonEventsApi.onBeforeLikeButtonClick\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([videoIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called after like button click completes (with updated state)
  func onAfterLikeButtonClick(videoId videoIdArg: String, isLiked isLikedArg: Bool, likeCount likeCountArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterButtonEventsApi.onAfterLikeButtonClick\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([videoIdArg, isLikedArg, likeCountArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when share button is clicked
  func onShareButtonClick(shareData shareDataArg: ShareData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterButtonEventsApi.onShareButtonClick\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([shareDataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
/// API for notifying native about screen and video state changes
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ReelsFlutterStateApiProtocol {
  /// Notify native when screen state changes
  func onScreenStateChanged(state stateArg: ScreenStateData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Notify native when video state changes
  func onVideoStateChanged(state stateArg: VideoStateData, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ReelsFlutterStateApi: ReelsFlutterStateApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonGeneratedPigeonCodec {
    return PigeonGeneratedPigeonCodec.shared
  }
  /// Notify native when screen state changes
  func onScreenStateChanged(state stateArg: ScreenStateData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterStateApi.onScreenStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Notify native when video state changes
  func onVideoStateChanged(state stateArg: VideoStateData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterStateApi.onVideoStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
/// API for handling navigation gestures
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ReelsFlutterNavigationApiProtocol {
  /// Called when user swipes left (to open My Room / user profile)
  func onSwipeLeft(userId userIdArg: String, userName userNameArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when user swipes right
  func onSwipeRight(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when user clicks on profile/user image
  func onUserProfileClick(userId userIdArg: String, userName userNameArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when user wants to dismiss/close the reels screen
  func dismissReels(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ReelsFlutterNavigationApi: ReelsFlutterNavigationApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonGeneratedPigeonCodec {
    return PigeonGeneratedPigeonCodec.shared
  }
  /// Called when user swipes left (to open My Room / user profile)
  func onSwipeLeft(userId userIdArg: String, userName userNameArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterNavigationApi.onSwipeLeft\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([userIdArg, userNameArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when user swipes right
  func onSwipeRight(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterNavigationApi.onSwipeRight\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when user clicks on profile/user image
  func onUserProfileClick(userId userIdArg: String, userName userNameArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterNavigationApi.onUserProfileClick\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([userIdArg, userNameArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when user wants to dismiss/close the reels screen
  func dismissReels(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterNavigationApi.dismissReels\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
/// API for managing Flutter lifecycle and state
/// Used to ensure each screen presentation is independent with fresh state
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ReelsFlutterLifecycleApiProtocol {
  /// Reset Flutter state for fresh screen start
  /// Clears video provider state, resets navigation, ensures independent screen
  func resetState(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Pause all resources (videos, network) when screen loses focus
  /// Called when screen is backgrounded or another screen is pushed on top
  func pauseAll(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Resume all resources when screen gains focus
  /// Called when screen returns to foreground or top of stack
  /// @param generation The generation number of the screen being resumed
  func resumeAll(generation generationArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ReelsFlutterLifecycleApi: ReelsFlutterLifecycleApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonGeneratedPigeonCodec {
    return PigeonGeneratedPigeonCodec.shared
  }
  /// Reset Flutter state for fresh screen start
  /// Clears video provider state, resets navigation, ensures independent screen
  func resetState(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterLifecycleApi.resetState\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Pause all resources (videos, network) when screen loses focus
  /// Called when screen is backgrounded or another screen is pushed on top
  func pauseAll(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterLifecycleApi.pauseAll\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Resume all resources when screen gains focus
  /// Called when screen returns to foreground or top of stack
  /// @param generation The generation number of the screen being resumed
  func resumeAll(generation generationArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reels_flutter.ReelsFlutterLifecycleApi.resumeAll\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([generationArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
